blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://mosecorg.github.io/mosec/
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/mosecorg/mosec/discussions/new/choose
    about: Ask a question or start a discussion
  - name: Chat on Discord
    url: https://discord.gg/Jq5vxuH69W
    about: Maybe chatting with the community can help
