{
 "title": "Mosec",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Scrape Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  {
   "title": "Mosec Service Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mosec_service_throughput" }
   ]
  },
  {
   "title": "Remaining Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "mosec_service_remaining_task" }
   ]
  },
  {
   "title": "Inference Result Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "inference_result_total" }
   ]
  },
  {
   "title": "Batch Size Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "mosec_service_batch_size_count" }
   ]
  }
 ]
}