global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: mosec_rust
    static_configs:
      - targets: ['mosec:8000']
  - job_name: mosec_python
    static_configs:
      - targets: ['mosec:5000']
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
