name: Nightly Test

on:
  schedule:
    - cron: "30 7 * * *"
  pull_request:
    paths:
      - ".github/workflows/nightly.yml"
      - "mosec/**"
      - "src/**"
      - "pyproject.toml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "tests/bad_req.py"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/nightly.yml"
      - "mosec/**"
      - "src/**"
      - "pyproject.toml"
      - "Cargo.lock"
      - "Cargo.toml"
      - "tests/bad_req.py"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  test:
    name: "stressful bad requests test"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
      - name: Install dependencies
        run: make install_py
      - name: Test
        run: make test_chaos
